package com.example.getyourlifeback

object MotivationalQuotes {
    private val quotes = listOf(
        // Career & Success
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "Your career is a marathon, not a sprint. Pace yourself wisely.",
        "The best time to plant a tree was 20 years ago. The second best time is now.",
        "Don't wait for opportunity. Create it.",
        "Your network is your net worth.",
        "Skills pay the bills, but passion pays the soul.",
        "Every expert was once a beginner.",
        "The only impossible journey is the one you never begin.",
        "Success is where preparation and opportunity meet.",
        "Your career is your responsibility, not your company's.",
        
        // Focus & Productivity
        "Focus is not about doing more things. It's about doing the right things.",
        "The successful warrior is the average person with laser-like focus.",
        "Where focus goes, energy flows and results show.",
        "Concentration is the secret of strength.",
        "Focus on being productive instead of busy.",
        "The art of being wise is knowing what to overlook.",
        "Multitasking is a lie. Focus on one thing at a time.",
        "Deep work is the superpower of the 21st century.",
        "Attention is the rarest and purest form of generosity.",
        "Focus is a matter of deciding what things you're not going to do.",
        
        // Mobile Addiction & Digital Wellness
        "Your phone is a tool, not a master. Use it wisely.",
        "The real world is more interesting than any screen.",
        "Digital detox is the new luxury.",
        "Don't let technology control your life. Control your technology.",
        "Every notification is someone else's priority, not yours.",
        "The most productive people are often the least connected.",
        "Your attention is your most valuable asset. Protect it.",
        "Social media is designed to be addictive. Be stronger than the design.",
        "Real connections happen when phones are put away.",
        "The quality of your life depends on the quality of your attention.",
        
        // Money & Wealth
        "Money is a terrible master but an excellent servant.",
        "It's not how much money you make, but how much you keep.",
        "The rich invest in time, the poor invest in money.",
        "Wealth is not about having a lot of money; it's about having options.",
        "The best investment you can make is in yourself.",
        "Don't save what is left after spending; spend what is left after saving.",
        "Rich people have small TVs and big libraries. Poor people have big TVs and small libraries.",
        "Money grows on the tree of persistence.",
        "The stock market is a device for transferring money from the impatient to the patient.",
        "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.",
        
        // Life & Wisdom
        "Life is what happens when you're busy making other plans.",
        "The purpose of life is not to be happy. It is to be useful, honorable, compassionate.",
        "Life is 10% what happens to you and 90% how you react to it.",
        "The biggest risk is not taking any risk.",
        "Time is more valuable than money. You can get more money, but you cannot get more time.",
        "Life begins at the end of your comfort zone.",
        "The only way to do great work is to love what you do.",
        "Life is short. Don't waste it on things that don't matter.",
        "Happiness is not a destination, it's a way of life.",
        "The best revenge is massive success.",
        
        // Additional Career Quotes
        "Choose a job you love, and you will never have to work a day in your life.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Don't be afraid to give up the good to go for the great.",
        "Innovation distinguishes between a leader and a follower.",
        "The way to get started is to quit talking and begin doing.",
        "It is during our darkest moments that we must focus to see the light.",
        "Believe you can and you're halfway there.",
        "The only person you are destined to become is the person you decide to be.",
        "Success is not about the destination, it's about the journey.",
        
        // Focus & Mindfulness
        "The present moment is the only time over which we have dominion.",
        "Mindfulness is about being fully awake in our lives.",
        "Focus on the step in front of you, not the whole staircase.",
        "The mind is everything. What you think you become.",
        "Wherever you are, be there totally.",
        "The ability to focus and to concentrate is among the most important skills you can develop.",
        "Single-tasking is the new multitasking.",
        "Focus is not about saying yes to the thing you've got to focus on. It's about saying no to the hundred other good ideas.",
        "The successful person has the habit of doing the things failures don't like to do.",
        "Discipline is choosing between what you want now and what you want most.",
        
        // Digital Minimalism
        "Simplicity is the ultimate sophistication.",
        "Less but better.",
        "The things you own end up owning you.",
        "Minimalism is not about having less. It's about making room for more of what matters.",
        "Digital minimalism is about being more intentional with technology.",
        "The best technology is the one you don't notice.",
        "Disconnect to reconnect.",
        "Your smartphone is making you stupid, antisocial and unhealthy. So why can't you put it down?",
        "The cure for anything is salt water: sweat, tears, or the sea. Not screen time.",
        "Real life is happening while you're staring at your phone.",
        
        // Wealth Building
        "Compound interest is the eighth wonder of the world.",
        "The rich don't work for money. They make money work for them.",
        "Assets put money in your pocket. Liabilities take money out of your pocket.",
        "The poor and middle class work for money. The rich have money work for them.",
        "It's not what you earn, it's what you keep.",
        "The most important investment you can make is in yourself.",
        "Rich people buy luxuries last, while the poor buy luxuries first.",
        "The real measure of your wealth is how much you'd be worth if you lost all your money.",
        "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
        "The habit of saving is itself an education; it fosters every virtue, teaches self-denial.",
        
        // Life Philosophy
        "The unexamined life is not worth living.",
        "Life is really simple, but we insist on making it complicated.",
        "The good life is one inspired by love and guided by knowledge.",
        "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
        "The meaning of life is to find your gift. The purpose of life is to give it away.",
        "Life is 10% what happens to you and 90% how you respond to it.",
        "The two most important days in your life are the day you are born and the day you find out why.",
        "Life is what we make it, always has been, always will be.",
        "The purpose of our lives is to be happy.",
        "Life is short, and it's up to you to make it sweet.",
        
        // Success Mindset
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "The road to success and the road to failure are almost exactly the same.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "Don't be afraid to fail. Be afraid not to try.",
        "Success is not about being the best. It's about being better than you were yesterday.",
        "The difference between successful people and really successful people is that really successful people say no to almost everything.",
        "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
        "The successful person makes a habit of doing what the failing person doesn't like to do.",
        "Success is the sum of small efforts repeated day in and day out.",
        "Success is not a destination, but the road that you're on.",
        
        // Time Management
        "Time is the most valuable thing we have, because it is the most irrevocable.",
        "The key is not to prioritize what's on your schedule, but to schedule your priorities.",
        "Time management is life management.",
        "You will never find time for anything. You must make it.",
        "Time is what we want most, but what we use worst.",
        "The bad news is time flies. The good news is you're the pilot.",
        "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.'",
        "Don't spend time beating on a wall, hoping to transform it into a door.",
        "Time is the coin of your life. It is the only coin you have, and only you can determine how it will be spent.",
        "The trouble is, you think you have time.",
        
        // Personal Growth
        "The only person you are destined to become is the person you decide to be.",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
        "The greatest revolution of our generation is the discovery that human beings can alter their lives by altering their attitudes of mind.",
        "Personal development is the belief that you are worth the effort, time, and energy needed to develop yourself.",
        "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
        "You are never too old to set another goal or to dream a new dream.",
        "The cave you fear to enter holds the treasure you seek.",
        "Your limitation—it's only your imagination.",
        "Great things never come from comfort zones.",
        "Don't limit your challenges. Challenge your limits.",
        
        // Entrepreneurship
        "The way to get started is to quit talking and begin doing.",
        "Innovation distinguishes between a leader and a follower.",
        "The biggest risk is not taking any risk.",
        "Entrepreneurship is living a few years of your life like most people won't, so that you can spend the rest of your life like most people can't.",
        "The entrepreneur always searches for change, responds to it, and exploits it as an opportunity.",
        "A business that makes nothing but money is a poor business.",
        "The best time to start was yesterday. The next best time is now.",
        "Don't worry about failure; you only have to be right once.",
        "The critical ingredient is getting off your butt and doing something.",
        "Entrepreneurship is about turning what excites you in life into capital.",
        
        // Leadership
        "A leader is one who knows the way, goes the way, and shows the way.",
        "Leadership is not about being in charge. It's about taking care of those in your charge.",
        "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.",
        "Leadership is the capacity to translate vision into reality.",
        "A good leader takes a little more than his share of the blame, a little less than his share of the credit.",
        "Leadership is not a position or a title, it is action and example.",
        "The art of leadership is saying no, not saying yes. It is very easy to say yes.",
        "Leadership is about making others better as a result of your presence and making sure that impact lasts in your absence.",
        "A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.",
        "Leadership is the ability to guide others without force into a direction or decision that leaves them still feeling empowered and accomplished.",
        
        // Motivation
        "The only impossible journey is the one you never begin.",
        "Believe you can and you're halfway there.",
        "It is during our darkest moments that we must focus to see the light.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "The only way to do great work is to love what you do.",
        "Don't watch the clock; do what it does. Keep going.",
        "The difference between ordinary and extraordinary is that little extra.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        
        // Financial Independence
        "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.",
        "The real measure of your wealth is how much you'd be worth if you lost all your money.",
        "It's not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for.",
        "The stock market is filled with individuals who know the price of everything, but the value of nothing.",
        "Risk comes from not knowing what you're doing.",
        "The most important investment you can make is in yourself.",
        "Never depend on single income. Make investment to create a second source.",
        "The habit of saving is itself an education; it fosters every virtue, teaches self-denial, cultivates the sense of order, trains to forethought.",
        "Wealth consists not in having great possessions, but in having few wants.",
        "The real measure of your wealth is how much you'd be worth if you lost all your money.",
        
        // Productivity
        "Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort.",
        "The key to productivity is to rotate your avoidance. You have to procrastinate on something.",
        "Being busy does not always mean real work. The object of all work is production or accomplishment.",
        "Focus on being productive instead of busy.",
        "Efficiency is doing things right; effectiveness is doing the right things.",
        "The way to get started is to quit talking and begin doing.",
        "You don't have to be great to get started, but you have to get started to be great.",
        "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
        "The secret of getting ahead is getting started.",
        "Productivity is being able to do things that you were never able to do before.",
        
        // More Career Quotes
        "Your career is a journey, not a destination.",
        "Hard work beats talent when talent doesn't work hard.",
        "The expert in anything was once a beginner.",
        "Success is the result of preparation, hard work, and learning from failure.",
        "Don't let what you cannot do interfere with what you can do.",
        "The only way to achieve the impossible is to believe it is possible.",
        "Excellence is not a skill, it's an attitude.",
        "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
        "The future depends on what you do today.",
        "Success isn't just about what you accomplish in your life, it's about what you inspire others to do.",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
        "The difference between who you are and who you want to be is what you do.",
        "Your potential is endless.",
        "Great things never come from comfort zones.",
        "Dream it. Wish it. Do it.",
        "Success doesn't just find you. You have to go out and get it.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream bigger. Do bigger.",
        "Don't stop when you're tired. Stop when you're done.",
        "Wake up with determination. Go to bed with satisfaction.",
        "Do something today that your future self will thank you for.",
        "Little things make big days.",
        "It's going to be hard, but hard does not mean impossible.",
        "Don't wait for opportunity. Create it.",
        "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
        "The key to success is to focus on goals, not obstacles.",
        "Dream it. Believe it. Build it.",
        
        // More Focus Quotes
        "Focus is the ultimate power that can change the way we think, the way we feel, and what we do in any moment.",
        "The successful person has the habit of doing the things failures don't like to do.",
        "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.",
        "Focus on the journey, not the destination. Joy is found not in finishing an activity but in doing it.",
        "The art of being wise is the art of knowing what to overlook.",
        "Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.",
        "Most people have no idea of the giant capacity we can immediately command when we focus all of our resources on mastering a single area of our lives.",
        "Successful people maintain a positive focus in life no matter what is going on around them.",
        "The main thing is to keep the main thing the main thing.",
        "Focus is about saying no to the hundred other good ideas that there are.",
        "Where your attention goes, your time goes.",
        "The ability to concentrate and to use your time well is everything if you want to succeed in business—or almost anywhere else for that matter.",
        "Focus on what you can control.",
        "The shorter way to do many things is to only do one thing at a time.",
        "Starve your distractions, feed your focus.",
        "Focus is not about doing more. Focus is about doing what matters.",
        "The key to success is to focus our conscious mind on things we desire not things we fear.",
        "Focus on the step in front of you, not the whole staircase.",
        "What you focus on expands.",
        "Focus is the bridge between thought and accomplishment.",
        
        // More Mobile Addiction Quotes
        "Technology is a useful servant but a dangerous master.",
        "The smartphone has become our security blanket. We reach for it when we're bored, anxious, or uncomfortable.",
        "We are becoming slaves to our own technology.",
        "The internet is the largest experiment in anarchy that we have ever had.",
        "Technology should improve your life, not become your life.",
        "Don't let your phone interrupt your life.",
        "The real question is not whether machines think but whether men do.",
        "We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.",
        "Technology is nothing. What's important is that you have a faith in people.",
        "The advance of technology is based on making it fit in so that you don't really even notice it.",
        "Any sufficiently advanced technology is indistinguishable from magic.",
        "The human spirit must prevail over technology.",
        "Technology is best when it brings people together.",
        "The real danger is not that computers will begin to think like men, but that men will begin to think like computers.",
        "We are stuck with technology when what we really want is just stuff that works.",
        "Technology is a word that describes something that doesn't work yet.",
        "The production of too many useful things results in too many useless people.",
        "Technology made large populations possible; large populations now make technology indispensable.",
        "Just because something doesn't do what you planned it to do doesn't mean it's useless.",
        "The machine does not isolate man from the great problems of nature but plunges him more deeply into them.",
        
        // More Money & Wealth Quotes
        "Money is a terrible master but an excellent servant.",
        "The lack of money is the root of all evil.",
        "A wise person should have money in their head, but not in their heart.",
        "Money often costs too much.",
        "The real measure of your wealth is how much you'd be worth if you lost all your money.",
        "It's not the man who has too little, but the man who craves more, who is poor.",
        "Wealth is the ability to fully experience life.",
        "The stock market is filled with individuals who know the price of everything, but the value of nothing.",
        "An investment in knowledge pays the best interest.",
        "Risk comes from not knowing what you're doing.",
        "The four most dangerous words in investing are: 'this time it's different.'",
        "Price is what you pay. Value is what you get.",
        "In the short run, the market is a voting machine but in the long run, it is a weighing machine.",
        "The stock market is a device for transferring money from the impatient to the patient.",
        "Our favorite holding period is forever.",
        "Rule No. 1: Never lose money. Rule No. 2: Never forget rule No. 1.",
        "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.",
        "Time is the friend of the wonderful company, the enemy of the mediocre.",
        "The most important investment you can make is in yourself.",
        "Don't put all your eggs in one basket.",
        
        // More Life Quotes
        "Life is what happens to you while you're busy making other plans.",
        "The purpose of our lives is to be happy.",
        "Life is really simple, but we insist on making it complicated.",
        "The good life is one inspired by love and guided by knowledge.",
        "In the end, it's not the years in your life that count. It's the life in your years.",
        "Life is 10% what happens to you and 90% how you react to it.",
        "The way I see it, if you want the rainbow, you gotta put up with the rain.",
        "Life is a succession of lessons which must be lived to be understood.",
        "Your time is limited, so don't waste it living someone else's life.",
        "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
        "The biggest adventure you can take is to live the life of your dreams.",
        "Life is short, and it's up to you to make it sweet.",
        "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.",
        "Life is what we make it, always has been, always will be.",
        "The meaning of life is to find your gift. The purpose of life is to give it away.",
        "Life isn't about getting and having, it's about giving and being.",
        "The two most important days in your life are the day you are born and the day you find out why.",
        "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
        "Life is 10% what you make it, and 90% how you take it.",
        "Life is like riding a bicycle. To keep your balance, you must keep moving.",
        
        // Success & Achievement
        "Success is not the key to happiness. Happiness is the key to success.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "The road to success and the road to failure are almost exactly the same.",
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "Don't be afraid to fail. Be afraid not to try.",
        "Success is not about being the best. It's about being better than you were yesterday.",
        "The difference between successful people and really successful people is that really successful people say no to almost everything.",
        "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
        "The successful person makes a habit of doing what the failing person doesn't like to do.",
        "Success is the sum of small efforts repeated day in and day out.",
        "Success is not a destination, but the road that you're on.",
        "Success is getting what you want, happiness is wanting what you get.",
        "The secret of success is to do the common thing uncommonly well.",
        "Success is where preparation and opportunity meet.",
        "Success is not measured by what you accomplish, but by the opposition you have encountered.",
        "Success is the ability to go from one failure to another with no loss of enthusiasm.",
        "Success is not about the destination, it's about the journey.",
        "Success is not about how much money you make, it's about the difference you make in people's lives.",
        "Success is not final, failure is not fatal, it is the courage to continue that counts.",
        "Success is not the absence of failure; it's the persistence through failure.",
        
        // Mindfulness & Present Moment
        "The present moment is the only time over which we have dominion.",
        "Mindfulness is about being fully awake in our lives.",
        "Wherever you are, be there totally.",
        "The mind is everything. What you think you become.",
        "Peace comes from within. Do not seek it without.",
        "The best way to take care of the future is to take care of the present moment.",
        "Yesterday is history, tomorrow is a mystery, today is a gift.",
        "The only moment we ever really have is now.",
        "Mindfulness is the aware, balanced acceptance of the present experience.",
        "Be present in all things and thankful for all things.",
        "The present is the only reality. The past is gone, the future is not yet here.",
        "Mindfulness isn't difficult, we just need to remember to do it.",
        "The little things? The little moments? They aren't little.",
        "Life is available only in the present moment.",
        "The present moment is filled with joy and happiness. If you are attentive, you will see it.",
        "Mindfulness is simply being aware of what is happening right now without wishing it were different.",
        "The art of living lies less in eliminating our troubles than in growing with them.",
        "Mindfulness is the miracle by which we master and restore ourselves.",
        "The present moment is the only moment available to us, and it is the door to all moments.",
        "Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves.",
        
        // Digital Detox & Minimalism
        "Simplicity is the ultimate sophistication.",
        "Less is more.",
        "The things you own end up owning you.",
        "Minimalism is not about having less. It's about making room for more of what matters.",
        "Clutter is not just physical stuff. It's old ideas, toxic relationships, and bad habits.",
        "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.",
        "It is not the man who has too little, but the man who craves more, who is poor.",
        "The more you have, the more you are occupied. The less you have, the more free you are.",
        "Minimalism is asking why before you buy.",
        "Live simply so that others may simply live.",
        "The best things in life aren't things.",
        "Reduce the complexity of life by eliminating the needless wants of life.",
        "The more you know, the less you need.",
        "Simplicity is not about deprivation. It's about having what you need and loving what you have.",
        "The ability to simplify means to eliminate the unnecessary so that the necessary may speak.",
        "Simplicity is the keynote of all true elegance.",
        "Live simply. Dream big. Be grateful. Give love. Laugh lots.",
        "The greatest wealth is to live content with little.",
        "Simplicity is the glory of expression.",
        "In character, in manner, in style, in all things, the supreme excellence is simplicity.",
        
        // Habits & Discipline
        "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
        "The chains of habit are too weak to be felt until they are too strong to be broken.",
        "Discipline is the bridge between goals and accomplishment.",
        "Motivation is what gets you started. Habit is what keeps you going.",
        "First we make our habits, then our habits make us.",
        "The successful person has the habit of doing the things failures don't like to do.",
        "Discipline is choosing between what you want now and what you want most.",
        "Good habits are worth being fanatical about.",
        "The groundwork for all happiness is good health.",
        "Take care of your body. It's the only place you have to live.",
        "Your net worth to the network is worth your network.",
        "Discipline is the soul of an army.",
        "Self-discipline is the magic power that makes you virtually unstoppable.",
        "Discipline is just choosing between what you want now and what you want most.",
        "The pain of discipline weighs ounces while the pain of regret weighs tons.",
        "Discipline is the foundation upon which all success is built.",
        "Without discipline, there's no life at all.",
        "Discipline is wisdom and vice versa.",
        "The first and best victory is to conquer self.",
        "He who conquers others is strong; He who conquers himself is mighty.",
        
        // Innovation & Creativity
        "Innovation distinguishes between a leader and a follower.",
        "The way to get started is to quit talking and begin doing.",
        "Creativity is intelligence having fun.",
        "The secret to creativity is knowing how to hide your sources.",
        "Creativity takes courage.",
        "You can't use up creativity. The more you use, the more you have.",
        "Creativity is contagious, pass it on.",
        "The creative adult is the child who survived.",
        "Creativity is seeing what everyone else has seen, and thinking what no one else has thought.",
        "Innovation is the specific instrument of entrepreneurship.",
        "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
        "Change is the end result of all true learning.",
        "Progress is impossible without change, and those who cannot change their minds cannot change anything.",
        "The measure of intelligence is the ability to change.",
        "If you don't like something, change it. If you can't change it, change your attitude.",
        "Be yourself; everyone else is already taken.",
        "The only impossible journey is the one you never begin.",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Imagination is more important than knowledge."
    )
    
    fun getRandomQuote(): String {
        return quotes.random()
    }
}